using System.Collections;
using System.Collections.Generic;
using UnityEngine;
namespace ET.Module.ETInput
{
    public enum InputCode
    {
        Right,
        Left,
        Up,
        Down,
        Jump,
        RotationRight,
        RotationLeft,
        //
        Interact,
        //
        Primary0,
        Primary1,
        Primary2,
        //
        Secondary0,
        Secondary1,
        Secondary2,
        //
        Skill0,
        Skill1,
        Skill2,
        Skill3,
        Skill4,
        Skill6,
        Skill7,
        Skill8,
        Skill9,
        //
        Item0,
        Item1,
        Item2,
        Item3,
        Item4,
        Item5,
        Item6,
        Item7,
        Item8,
        Item9,
        //
        Speed0,
        Speed1,
        Speed2,
        //
        Stand0,
        Stand1,
        Stand2,
        // 
        Reload,
        Recharge,
        LeanLeft,
        LeanRight,
        //
        Dash,
        Dodge,
        Block,
        //
        Pause,
        Menu,
        Quicksave,
        Quickload,
        //dialog
        DialogContinue,
        DialogAuto,
        DialogPause,
        DialogSkip,
        //menu 
        Accept,
        Cancle,
        //camera
        CameraPan,
        //uI
        UI0,
        UI1,
        UI2,
        UI3,
        UI4,
        UI5,
        UI6,
        UI7,
        UI8,
        UI9,
    }
}
